apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  generation: 3
  name: production-scan-placement
  namespace: policies-troubleshoot
spec:
  clusterSets:
  - default
  tolerations:
  - key: cluster.open-cluster-management.io/unreachable
    operator: Exists
  - key: cluster.open-cluster-management.io/unavailable
    operator: Exists
