---
apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: task-list
  name: task-list
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: task-list
              image: registry.ocp4.example.com:8443/rhel9/support-tools:9.3
              command:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
